Models/EmprestimosModel.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }


       

        [Required (ErrorMessage = "Deve conter o nome do Recebedor")]
        public string Recebedor  { get; set; }


        [Required (ErrorMessage = "Deve conter o nome do Fornecedor")]
        public string Fornecedor  { get; set; }
        
        
        [Required (ErrorMessage = "Deve conter o nome do Livro")]
        public string LivroEmprestado  { get; set; }
        public DateTime DataUltimaAtualizacao  { get; set; } = DateTime.Now;




    }
}

Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmprestimoController.cs
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;

namespace Emprestimo.Controllers
{
    public class EmprestimoController : Controller
    {
        readonly private AppDbContext _db;

        public EmprestimoController(AppDbContext db)
        {
            _db = db;


        }
        public IActionResult Index()
        {

            IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos;

            return View(emprestimos);
        }


        public IActionResult Cadastro() {

            return View();

        }

        [HttpPost]
        public IActionResult Cadastro(EmprestimosModel emprestimos)
        {

            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimos);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }

            return RedirectToAction("Update");

        }

        [HttpGet]
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();

            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(e => e.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);


        }
        [HttpPost]
        public IActionResult Update(EmprestimosModel emprestimo)
        {

            if (ModelState.IsValid) {

                _db.Emprestimos.Update(emprestimo);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(emprestimo);



        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();

            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(e => e.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }




        [HttpPost]
        public IActionResult Delete(EmprestimosModel emprestimo)
        {

            if (emprestimo == null )
            {
                return NotFound();
               
            }
                _db.Emprestimos.Remove(emprestimo);
                _db.SaveChanges();

                
            
           return RedirectToAction("Index");
        }


    }
}

Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emprestimo/Cadastro.cshtml
@model EmprestimosModel


@{
	ViewData["title"] = "Tela de cadastro";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center"  >
        <h1 class="text-light">Cadastro</h1>
        </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Cadastro">
     
        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor"   placeholder="Quem vai recebero Livro">
            <span class="text-danger" asp-validation-for="Recebedor" ></span>

        </div>
        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor"  id="Fornecedor"   placeholder="Quem esta emprestando o livro">
            <span class="text-danger" asp-validation-for="Fornecedor" ></span>

        </div>
        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro"  placeholder="Qual o livro emprestado">
            <span class="text-danger" asp-validation-for="LivroEmprestado" ></span>

        </div>
       
        
        <div class="d-flex gap-5 mt-5">

            <button type="submit" class="btn btn-success w-50">Cadastrar</button>
            <a class="btn btn-primary mx-2 w-50"  asp-action="">Voltar</a>

        </div>
    </form>

</div>

Views/Emprestimo/Delete.cshtml
@model EmprestimosModel


@{
    ViewData["title"] = "Tela de Excluir";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-warning">Excluir Registros</h1>
        <h2 class="text-danger">Deseja realmente apagar o Registro?</h2>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Delete">
        <input type="hidden" asp-for="Id" />


        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" asp-route-value="@Model.Recebedor " id="Recebedor" placeholder="Quem vai recebero Livro" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>

        </div>
        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem esta emprestando o livro" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>

        </div>
        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual o livro emprestado" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>

        </div>


        <div class="d-flex gap-5 mt-5">

            <button type="submit" class="btn btn-success w-50">Excluir</button>
            <a class="btn btn-primary mx-2 w-50" asp-action="">Voltar</a>

        </div>
    </form>

</div>

Views/Emprestimo/Index.cshtml
@{
    ViewData["title"] = "Tela de listagem";
}

@model IEnumerable<EmprestimosModel>




    <div class="container text-center">

    
            <div class="d-flex justify-content-between align-items-center mb-5">

        <h1>Lista de Livros Emprestados</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastro">Cadastro</a>
            </div>

   

    
    


<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Data Emprestimo
                   
            </th>
            
                
        </tr>
    </thead>
    <tbody>

        @if(Model != null){


            @foreach (var emprestimos in Model)
            {
            <tr>
                <th scope="row">@emprestimos.Recebedor 

                </th>
                <td>@emprestimos.Fornecedor</td>
                <td>@emprestimos.LivroEmprestado</td>
                <td>@emprestimos.DataUltimaAtualizacao</td>
                <td>

                            <a class="btn btn-warning" asp-controller="Emprestimo" asp-action="Update" asp-route-id="@emprestimos.Id" >Update</a>
                            <a class="btn btn-danger" asp-controller="Emprestimo" asp-action="Delete" asp-route-id="@emprestimos.Id" >Delete</a>
                 </td>
            </tr>
            }

        }
        else
        {
            <tr>
                <th scope="row">Não encontrado</th>
                <td>Não encontrado</td>
                <td>Não encontrado</td>
                <td>Não encontrado</td>
            </tr>

        }


      
      
    </tbody>
</table>
</div>

Views/Emprestimo/Update.cshtml
@model EmprestimosModel


@{
	ViewData["title"] = "Tela de Atualizalção";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center"  >
        <h1 class="text-light">Atualizar Dados</h1>
        </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Update">
        <input type="hidden" asp-for="Id" />


        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" asp-route-value="@Model.Recebedor " id="Recebedor" placeholder="Quem vai recebero Livro">
            <span class="text-danger" asp-validation-for="Recebedor" ></span>

        </div>
        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor"  id="Fornecedor" placeholder="Quem esta emprestando o livro">
            <span class="text-danger" asp-validation-for="Fornecedor" ></span>

        </div>
        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual o livro emprestado">
            <span class="text-danger" asp-validation-for="LivroEmprestado" ></span>

        </div>
       
        
        <div class="d-flex gap-5 mt-5">

            <button type="submit" class="btn btn-success w-50">Atualizar</button>
            <a class="btn btn-primary mx-2 w-50"  asp-action="">Voltar</a>

        </div>
    </form>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmprestimoLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Emprestimo" asp-action="Index"><h1>Emprestimo De Livros</h1></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               @*  <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimo</a>
                        </li>
                    </ul>
                </div> *@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EmprestimoLivros - <a asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimo</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>